// Code generated by protoc-gen-go. DO NOT EDIT.
// source: portfolio.proto

package portfolio

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Order_Ordertype int32

const (
	Order_BUY  Order_Ordertype = 0
	Order_SELL Order_Ordertype = 1
)

var Order_Ordertype_name = map[int32]string{
	0: "BUY",
	1: "SELL",
}

var Order_Ordertype_value = map[string]int32{
	"BUY":  0,
	"SELL": 1,
}

func (x Order_Ordertype) String() string {
	return proto.EnumName(Order_Ordertype_name, int32(x))
}

func (Order_Ordertype) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_c193a9c2ca89d2ee, []int{2, 0}
}

type Date struct {
	Year                 int32    `protobuf:"varint,1,opt,name=year,proto3" json:"year,omitempty"`
	Month                int32    `protobuf:"varint,2,opt,name=month,proto3" json:"month,omitempty"`
	Day                  int32    `protobuf:"varint,3,opt,name=day,proto3" json:"day,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Date) Reset()         { *m = Date{} }
func (m *Date) String() string { return proto.CompactTextString(m) }
func (*Date) ProtoMessage()    {}
func (*Date) Descriptor() ([]byte, []int) {
	return fileDescriptor_c193a9c2ca89d2ee, []int{0}
}

func (m *Date) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Date.Unmarshal(m, b)
}
func (m *Date) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Date.Marshal(b, m, deterministic)
}
func (m *Date) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Date.Merge(m, src)
}
func (m *Date) XXX_Size() int {
	return xxx_messageInfo_Date.Size(m)
}
func (m *Date) XXX_DiscardUnknown() {
	xxx_messageInfo_Date.DiscardUnknown(m)
}

var xxx_messageInfo_Date proto.InternalMessageInfo

func (m *Date) GetYear() int32 {
	if m != nil {
		return m.Year
	}
	return 0
}

func (m *Date) GetMonth() int32 {
	if m != nil {
		return m.Month
	}
	return 0
}

func (m *Date) GetDay() int32 {
	if m != nil {
		return m.Day
	}
	return 0
}

type Holdings struct {
	Symbol               string   `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Quantity             int32    `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	BuyValue             float64  `protobuf:"fixed64,3,opt,name=buyValue,proto3" json:"buyValue,omitempty"`
	SellValue            float64  `protobuf:"fixed64,4,opt,name=sellValue,proto3" json:"sellValue,omitempty"`
	Orders               []*Order `protobuf:"bytes,5,rep,name=orders,proto3" json:"orders,omitempty"`
	CurrentValue         float64  `protobuf:"fixed64,6,opt,name=currentValue,proto3" json:"currentValue,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Holdings) Reset()         { *m = Holdings{} }
func (m *Holdings) String() string { return proto.CompactTextString(m) }
func (*Holdings) ProtoMessage()    {}
func (*Holdings) Descriptor() ([]byte, []int) {
	return fileDescriptor_c193a9c2ca89d2ee, []int{1}
}

func (m *Holdings) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Holdings.Unmarshal(m, b)
}
func (m *Holdings) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Holdings.Marshal(b, m, deterministic)
}
func (m *Holdings) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Holdings.Merge(m, src)
}
func (m *Holdings) XXX_Size() int {
	return xxx_messageInfo_Holdings.Size(m)
}
func (m *Holdings) XXX_DiscardUnknown() {
	xxx_messageInfo_Holdings.DiscardUnknown(m)
}

var xxx_messageInfo_Holdings proto.InternalMessageInfo

func (m *Holdings) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

func (m *Holdings) GetQuantity() int32 {
	if m != nil {
		return m.Quantity
	}
	return 0
}

func (m *Holdings) GetBuyValue() float64 {
	if m != nil {
		return m.BuyValue
	}
	return 0
}

func (m *Holdings) GetSellValue() float64 {
	if m != nil {
		return m.SellValue
	}
	return 0
}

func (m *Holdings) GetOrders() []*Order {
	if m != nil {
		return m.Orders
	}
	return nil
}

func (m *Holdings) GetCurrentValue() float64 {
	if m != nil {
		return m.CurrentValue
	}
	return 0
}

type Order struct {
	OrderId              int64           `protobuf:"varint,1,opt,name=orderId,proto3" json:"orderId,omitempty"`
	Symbol               string          `protobuf:"bytes,2,opt,name=symbol,proto3" json:"symbol,omitempty"`
	OrderFee             float64         `protobuf:"fixed64,3,opt,name=orderFee,proto3" json:"orderFee,omitempty"`
	Ordertype            Order_Ordertype `protobuf:"varint,4,opt,name=ordertype,proto3,enum=Order_Ordertype" json:"ordertype,omitempty"`
	Price                float64         `protobuf:"fixed64,5,opt,name=price,proto3" json:"price,omitempty"`
	Quantity             int32           `protobuf:"varint,6,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Completiondate       *Date           `protobuf:"bytes,7,opt,name=completiondate,proto3" json:"completiondate,omitempty"`
	AccountId            string          `protobuf:"bytes,8,opt,name=accountId,proto3" json:"accountId,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Order) Reset()         { *m = Order{} }
func (m *Order) String() string { return proto.CompactTextString(m) }
func (*Order) ProtoMessage()    {}
func (*Order) Descriptor() ([]byte, []int) {
	return fileDescriptor_c193a9c2ca89d2ee, []int{2}
}

func (m *Order) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Order.Unmarshal(m, b)
}
func (m *Order) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Order.Marshal(b, m, deterministic)
}
func (m *Order) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Order.Merge(m, src)
}
func (m *Order) XXX_Size() int {
	return xxx_messageInfo_Order.Size(m)
}
func (m *Order) XXX_DiscardUnknown() {
	xxx_messageInfo_Order.DiscardUnknown(m)
}

var xxx_messageInfo_Order proto.InternalMessageInfo

func (m *Order) GetOrderId() int64 {
	if m != nil {
		return m.OrderId
	}
	return 0
}

func (m *Order) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

func (m *Order) GetOrderFee() float64 {
	if m != nil {
		return m.OrderFee
	}
	return 0
}

func (m *Order) GetOrdertype() Order_Ordertype {
	if m != nil {
		return m.Ordertype
	}
	return Order_BUY
}

func (m *Order) GetPrice() float64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *Order) GetQuantity() int32 {
	if m != nil {
		return m.Quantity
	}
	return 0
}

func (m *Order) GetCompletiondate() *Date {
	if m != nil {
		return m.Completiondate
	}
	return nil
}

func (m *Order) GetAccountId() string {
	if m != nil {
		return m.AccountId
	}
	return ""
}

type Portfolio struct {
	AccountId            string               `protobuf:"bytes,1,opt,name=accountId,proto3" json:"accountId,omitempty"`
	Name                 string               `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	CurrentTotalValue    float64              `protobuf:"fixed64,3,opt,name=currentTotalValue,proto3" json:"currentTotalValue,omitempty"`
	BuyValue             float64              `protobuf:"fixed64,4,opt,name=buyValue,proto3" json:"buyValue,omitempty"`
	SellValue            float64              `protobuf:"fixed64,5,opt,name=sellValue,proto3" json:"sellValue,omitempty"`
	Holdings             map[string]*Holdings `protobuf:"bytes,6,rep,name=holdings,proto3" json:"holdings,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Portfolio) Reset()         { *m = Portfolio{} }
func (m *Portfolio) String() string { return proto.CompactTextString(m) }
func (*Portfolio) ProtoMessage()    {}
func (*Portfolio) Descriptor() ([]byte, []int) {
	return fileDescriptor_c193a9c2ca89d2ee, []int{3}
}

func (m *Portfolio) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Portfolio.Unmarshal(m, b)
}
func (m *Portfolio) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Portfolio.Marshal(b, m, deterministic)
}
func (m *Portfolio) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Portfolio.Merge(m, src)
}
func (m *Portfolio) XXX_Size() int {
	return xxx_messageInfo_Portfolio.Size(m)
}
func (m *Portfolio) XXX_DiscardUnknown() {
	xxx_messageInfo_Portfolio.DiscardUnknown(m)
}

var xxx_messageInfo_Portfolio proto.InternalMessageInfo

func (m *Portfolio) GetAccountId() string {
	if m != nil {
		return m.AccountId
	}
	return ""
}

func (m *Portfolio) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Portfolio) GetCurrentTotalValue() float64 {
	if m != nil {
		return m.CurrentTotalValue
	}
	return 0
}

func (m *Portfolio) GetBuyValue() float64 {
	if m != nil {
		return m.BuyValue
	}
	return 0
}

func (m *Portfolio) GetSellValue() float64 {
	if m != nil {
		return m.SellValue
	}
	return 0
}

func (m *Portfolio) GetHoldings() map[string]*Holdings {
	if m != nil {
		return m.Holdings
	}
	return nil
}

type PortfolioRequest struct {
	AccountId            string   `protobuf:"bytes,1,opt,name=accountId,proto3" json:"accountId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PortfolioRequest) Reset()         { *m = PortfolioRequest{} }
func (m *PortfolioRequest) String() string { return proto.CompactTextString(m) }
func (*PortfolioRequest) ProtoMessage()    {}
func (*PortfolioRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c193a9c2ca89d2ee, []int{4}
}

func (m *PortfolioRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PortfolioRequest.Unmarshal(m, b)
}
func (m *PortfolioRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PortfolioRequest.Marshal(b, m, deterministic)
}
func (m *PortfolioRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PortfolioRequest.Merge(m, src)
}
func (m *PortfolioRequest) XXX_Size() int {
	return xxx_messageInfo_PortfolioRequest.Size(m)
}
func (m *PortfolioRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PortfolioRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PortfolioRequest proto.InternalMessageInfo

func (m *PortfolioRequest) GetAccountId() string {
	if m != nil {
		return m.AccountId
	}
	return ""
}

type PortfolioResponse struct {
	Portfolio            *Portfolio `protobuf:"bytes,1,opt,name=portfolio,proto3" json:"portfolio,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *PortfolioResponse) Reset()         { *m = PortfolioResponse{} }
func (m *PortfolioResponse) String() string { return proto.CompactTextString(m) }
func (*PortfolioResponse) ProtoMessage()    {}
func (*PortfolioResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c193a9c2ca89d2ee, []int{5}
}

func (m *PortfolioResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PortfolioResponse.Unmarshal(m, b)
}
func (m *PortfolioResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PortfolioResponse.Marshal(b, m, deterministic)
}
func (m *PortfolioResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PortfolioResponse.Merge(m, src)
}
func (m *PortfolioResponse) XXX_Size() int {
	return xxx_messageInfo_PortfolioResponse.Size(m)
}
func (m *PortfolioResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PortfolioResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PortfolioResponse proto.InternalMessageInfo

func (m *PortfolioResponse) GetPortfolio() *Portfolio {
	if m != nil {
		return m.Portfolio
	}
	return nil
}

type OrderRequest struct {
	AccountId            string   `protobuf:"bytes,1,opt,name=accountId,proto3" json:"accountId,omitempty"`
	Order                *Order   `protobuf:"bytes,2,opt,name=order,proto3" json:"order,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OrderRequest) Reset()         { *m = OrderRequest{} }
func (m *OrderRequest) String() string { return proto.CompactTextString(m) }
func (*OrderRequest) ProtoMessage()    {}
func (*OrderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c193a9c2ca89d2ee, []int{6}
}

func (m *OrderRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderRequest.Unmarshal(m, b)
}
func (m *OrderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderRequest.Marshal(b, m, deterministic)
}
func (m *OrderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderRequest.Merge(m, src)
}
func (m *OrderRequest) XXX_Size() int {
	return xxx_messageInfo_OrderRequest.Size(m)
}
func (m *OrderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_OrderRequest proto.InternalMessageInfo

func (m *OrderRequest) GetAccountId() string {
	if m != nil {
		return m.AccountId
	}
	return ""
}

func (m *OrderRequest) GetOrder() *Order {
	if m != nil {
		return m.Order
	}
	return nil
}

type OrderResponse struct {
	OrderNumber          string   `protobuf:"bytes,1,opt,name=orderNumber,proto3" json:"orderNumber,omitempty"`
	AccountId            string   `protobuf:"bytes,2,opt,name=accountId,proto3" json:"accountId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OrderResponse) Reset()         { *m = OrderResponse{} }
func (m *OrderResponse) String() string { return proto.CompactTextString(m) }
func (*OrderResponse) ProtoMessage()    {}
func (*OrderResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c193a9c2ca89d2ee, []int{7}
}

func (m *OrderResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderResponse.Unmarshal(m, b)
}
func (m *OrderResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderResponse.Marshal(b, m, deterministic)
}
func (m *OrderResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderResponse.Merge(m, src)
}
func (m *OrderResponse) XXX_Size() int {
	return xxx_messageInfo_OrderResponse.Size(m)
}
func (m *OrderResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderResponse.DiscardUnknown(m)
}

var xxx_messageInfo_OrderResponse proto.InternalMessageInfo

func (m *OrderResponse) GetOrderNumber() string {
	if m != nil {
		return m.OrderNumber
	}
	return ""
}

func (m *OrderResponse) GetAccountId() string {
	if m != nil {
		return m.AccountId
	}
	return ""
}

func init() {
	proto.RegisterEnum("Order_Ordertype", Order_Ordertype_name, Order_Ordertype_value)
	proto.RegisterType((*Date)(nil), "Date")
	proto.RegisterType((*Holdings)(nil), "Holdings")
	proto.RegisterType((*Order)(nil), "Order")
	proto.RegisterType((*Portfolio)(nil), "Portfolio")
	proto.RegisterMapType((map[string]*Holdings)(nil), "Portfolio.HoldingsEntry")
	proto.RegisterType((*PortfolioRequest)(nil), "PortfolioRequest")
	proto.RegisterType((*PortfolioResponse)(nil), "PortfolioResponse")
	proto.RegisterType((*OrderRequest)(nil), "OrderRequest")
	proto.RegisterType((*OrderResponse)(nil), "OrderResponse")
}

func init() { proto.RegisterFile("portfolio.proto", fileDescriptor_c193a9c2ca89d2ee) }

var fileDescriptor_c193a9c2ca89d2ee = []byte{
	// 571 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x54, 0x4d, 0x6f, 0xd3, 0x40,
	0x10, 0xc5, 0x4e, 0xec, 0xc6, 0x93, 0x36, 0x24, 0x2b, 0x84, 0xac, 0xa8, 0x2a, 0x91, 0x4f, 0x39,
	0x14, 0x0b, 0x05, 0x90, 0x10, 0x12, 0x97, 0x8a, 0x56, 0x14, 0x55, 0x14, 0x6d, 0x01, 0x89, 0xa3,
	0x63, 0x2f, 0x6d, 0x84, 0xe3, 0x75, 0xd7, 0xeb, 0x22, 0xff, 0x1e, 0xf8, 0x19, 0xfc, 0x38, 0xb4,
	0xb3, 0x1b, 0x7f, 0x55, 0xaa, 0xb8, 0x44, 0x33, 0x6f, 0x76, 0xdf, 0xcc, 0x3c, 0xbf, 0x0d, 0x3c,
	0xce, 0xb9, 0x90, 0x3f, 0x78, 0xba, 0xe1, 0x61, 0x2e, 0xb8, 0xe4, 0xc1, 0x09, 0x0c, 0xdf, 0x47,
	0x92, 0x11, 0x02, 0xc3, 0x8a, 0x45, 0xc2, 0xb7, 0x16, 0xd6, 0xd2, 0xa1, 0x18, 0x93, 0x27, 0xe0,
	0x6c, 0x79, 0x26, 0x6f, 0x7c, 0x1b, 0x41, 0x9d, 0x90, 0x29, 0x0c, 0x92, 0xa8, 0xf2, 0x07, 0x88,
	0xa9, 0x30, 0xf8, 0x6b, 0xc1, 0xe8, 0x03, 0x4f, 0x93, 0x4d, 0x76, 0x5d, 0x90, 0xa7, 0xe0, 0x16,
	0xd5, 0x76, 0xcd, 0x53, 0xa4, 0xf2, 0xa8, 0xc9, 0xc8, 0x1c, 0x46, 0xb7, 0x65, 0x94, 0xc9, 0x8d,
	0xac, 0x0c, 0x5f, 0x9d, 0xab, 0xda, 0xba, 0xac, 0xbe, 0x45, 0x69, 0xc9, 0x90, 0xd7, 0xa2, 0x75,
	0x4e, 0x0e, 0xc1, 0x2b, 0x58, 0x9a, 0xea, 0xe2, 0x10, 0x8b, 0x0d, 0x40, 0x8e, 0xc0, 0xe5, 0x22,
	0x61, 0xa2, 0xf0, 0x9d, 0xc5, 0x60, 0x39, 0x5e, 0xb9, 0xe1, 0xa5, 0x4a, 0xa9, 0x41, 0x49, 0x00,
	0xfb, 0x71, 0x29, 0x04, 0xcb, 0xa4, 0x26, 0x70, 0x91, 0xa0, 0x83, 0x05, 0x7f, 0x6c, 0x70, 0xf0,
	0x16, 0xf1, 0x61, 0x0f, 0xef, 0x9d, 0x27, 0x38, 0xfc, 0x80, 0xee, 0xd2, 0xd6, 0x56, 0x76, 0x7f,
	0x2b, 0x3c, 0x72, 0xc6, 0xea, 0xc9, 0x77, 0x39, 0x09, 0xc1, 0xc3, 0x58, 0x56, 0xb9, 0x9e, 0x7c,
	0xb2, 0x9a, 0xea, 0xf1, 0xf4, 0xaf, 0xc2, 0x69, 0x73, 0x44, 0xc9, 0x9d, 0x8b, 0x4d, 0xcc, 0x7c,
	0x07, 0x89, 0x74, 0xd2, 0xd1, 0xcd, 0xed, 0xe9, 0xf6, 0x1c, 0x26, 0x31, 0xdf, 0xe6, 0x29, 0x93,
	0x1b, 0x9e, 0x25, 0x91, 0x64, 0xfe, 0xde, 0xc2, 0x5a, 0x8e, 0x57, 0x4e, 0xa8, 0xbe, 0x29, 0xed,
	0x15, 0x95, 0x94, 0x51, 0x1c, 0xf3, 0x32, 0x93, 0xe7, 0x89, 0x3f, 0xc2, 0x3d, 0x1a, 0x20, 0x38,
	0x02, 0xaf, 0x1e, 0x8b, 0xec, 0xc1, 0xe0, 0xe4, 0xeb, 0xf7, 0xe9, 0x23, 0x32, 0x82, 0xe1, 0xd5,
	0xe9, 0xc5, 0xc5, 0xd4, 0x0a, 0x7e, 0xdb, 0xe0, 0x7d, 0xde, 0xb9, 0xa7, 0xcb, 0x65, 0xf5, 0xb8,
	0x94, 0x9b, 0xb2, 0x68, 0xcb, 0x8c, 0x58, 0x18, 0x93, 0x63, 0x98, 0x19, 0xd9, 0xbf, 0x70, 0x19,
	0xa5, 0xed, 0xaf, 0x7d, 0xbf, 0xd0, 0xb1, 0xc4, 0xf0, 0x21, 0x4b, 0x38, 0x7d, 0x4b, 0xbc, 0x82,
	0xd1, 0x8d, 0x31, 0xa3, 0xef, 0xa2, 0x29, 0xfc, 0xb0, 0x9e, 0x3b, 0xdc, 0xf9, 0xf4, 0x34, 0x93,
	0xa2, 0xa2, 0xf5, 0xc9, 0xf9, 0x19, 0x1c, 0x74, 0x4a, 0xca, 0xe6, 0x3f, 0x59, 0x65, 0x56, 0x53,
	0x21, 0x79, 0x06, 0xce, 0x1d, 0xb6, 0xb4, 0x51, 0x64, 0xaf, 0xe6, 0xa2, 0x1a, 0x7f, 0x6b, 0xbf,
	0xb1, 0x82, 0x17, 0x30, 0xad, 0x9b, 0x51, 0x76, 0x5b, 0xb2, 0x42, 0x3e, 0xac, 0x55, 0xf0, 0x0e,
	0x66, 0xad, 0x1b, 0x45, 0xce, 0xb3, 0x82, 0x91, 0x25, 0x78, 0xf5, 0x4b, 0xc5, 0x2b, 0xe3, 0x15,
	0x34, 0x5b, 0xd0, 0xa6, 0x18, 0x7c, 0x84, 0x7d, 0x6d, 0xf9, 0xff, 0x69, 0x46, 0x0e, 0xc1, 0x41,
	0xc3, 0x99, 0x1d, 0x76, 0xcf, 0x45, 0x83, 0xc1, 0x25, 0x1c, 0x18, 0x2e, 0x33, 0xc6, 0x02, 0xc6,
	0x58, 0xf9, 0x54, 0x6e, 0xd7, 0x4c, 0x18, 0xba, 0x36, 0xd4, 0x6d, 0x67, 0xf7, 0xda, 0xad, 0x7e,
	0xb5, 0xd4, 0xb8, 0x62, 0xe2, 0x4e, 0x19, 0xfa, 0x35, 0xec, 0x5f, 0x33, 0xd9, 0x38, 0x69, 0x16,
	0xf6, 0x05, 0x9b, 0x93, 0xf0, 0xbe, 0x22, 0xc7, 0x30, 0x8e, 0x05, 0x8b, 0x24, 0xd3, 0x4f, 0xf5,
	0x20, 0x6c, 0x6f, 0x3d, 0x9f, 0x84, 0x9d, 0xc1, 0xd7, 0x2e, 0xfe, 0xbb, 0xbd, 0xfc, 0x17, 0x00,
	0x00, 0xff, 0xff, 0xf0, 0x6c, 0x7a, 0xa8, 0xf0, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PortfolioServiceClient is the client API for PortfolioService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PortfolioServiceClient interface {
	GetPortfolio(ctx context.Context, in *PortfolioRequest, opts ...grpc.CallOption) (*PortfolioResponse, error)
	CreateOrder(ctx context.Context, in *OrderRequest, opts ...grpc.CallOption) (*OrderResponse, error)
}

type portfolioServiceClient struct {
	cc *grpc.ClientConn
}

func NewPortfolioServiceClient(cc *grpc.ClientConn) PortfolioServiceClient {
	return &portfolioServiceClient{cc}
}

func (c *portfolioServiceClient) GetPortfolio(ctx context.Context, in *PortfolioRequest, opts ...grpc.CallOption) (*PortfolioResponse, error) {
	out := new(PortfolioResponse)
	err := c.cc.Invoke(ctx, "/PortfolioService/getPortfolio", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *portfolioServiceClient) CreateOrder(ctx context.Context, in *OrderRequest, opts ...grpc.CallOption) (*OrderResponse, error) {
	out := new(OrderResponse)
	err := c.cc.Invoke(ctx, "/PortfolioService/createOrder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PortfolioServiceServer is the server API for PortfolioService service.
type PortfolioServiceServer interface {
	GetPortfolio(context.Context, *PortfolioRequest) (*PortfolioResponse, error)
	CreateOrder(context.Context, *OrderRequest) (*OrderResponse, error)
}

// UnimplementedPortfolioServiceServer can be embedded to have forward compatible implementations.
type UnimplementedPortfolioServiceServer struct {
}

func (*UnimplementedPortfolioServiceServer) GetPortfolio(ctx context.Context, req *PortfolioRequest) (*PortfolioResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPortfolio not implemented")
}
func (*UnimplementedPortfolioServiceServer) CreateOrder(ctx context.Context, req *OrderRequest) (*OrderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateOrder not implemented")
}

func RegisterPortfolioServiceServer(s *grpc.Server, srv PortfolioServiceServer) {
	s.RegisterService(&_PortfolioService_serviceDesc, srv)
}

func _PortfolioService_GetPortfolio_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PortfolioRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PortfolioServiceServer).GetPortfolio(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/PortfolioService/GetPortfolio",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PortfolioServiceServer).GetPortfolio(ctx, req.(*PortfolioRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PortfolioService_CreateOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PortfolioServiceServer).CreateOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/PortfolioService/CreateOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PortfolioServiceServer).CreateOrder(ctx, req.(*OrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _PortfolioService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "PortfolioService",
	HandlerType: (*PortfolioServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "getPortfolio",
			Handler:    _PortfolioService_GetPortfolio_Handler,
		},
		{
			MethodName: "createOrder",
			Handler:    _PortfolioService_CreateOrder_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "portfolio.proto",
}
