// Code generated by protoc-gen-go. DO NOT EDIT.
// source: account.proto

package account

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type LoginInfo struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginInfo) Reset()         { *m = LoginInfo{} }
func (m *LoginInfo) String() string { return proto.CompactTextString(m) }
func (*LoginInfo) ProtoMessage()    {}
func (*LoginInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{0}
}

func (m *LoginInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginInfo.Unmarshal(m, b)
}
func (m *LoginInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginInfo.Marshal(b, m, deterministic)
}
func (m *LoginInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginInfo.Merge(m, src)
}
func (m *LoginInfo) XXX_Size() int {
	return xxx_messageInfo_LoginInfo.Size(m)
}
func (m *LoginInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginInfo.DiscardUnknown(m)
}

var xxx_messageInfo_LoginInfo proto.InternalMessageInfo

func (m *LoginInfo) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *LoginInfo) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type CreditCardInfo struct {
	CardNumber           string   `protobuf:"bytes,1,opt,name=cardNumber,proto3" json:"cardNumber,omitempty"`
	Cvc                  string   `protobuf:"bytes,2,opt,name=cvc,proto3" json:"cvc,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreditCardInfo) Reset()         { *m = CreditCardInfo{} }
func (m *CreditCardInfo) String() string { return proto.CompactTextString(m) }
func (*CreditCardInfo) ProtoMessage()    {}
func (*CreditCardInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{1}
}

func (m *CreditCardInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreditCardInfo.Unmarshal(m, b)
}
func (m *CreditCardInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreditCardInfo.Marshal(b, m, deterministic)
}
func (m *CreditCardInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreditCardInfo.Merge(m, src)
}
func (m *CreditCardInfo) XXX_Size() int {
	return xxx_messageInfo_CreditCardInfo.Size(m)
}
func (m *CreditCardInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_CreditCardInfo.DiscardUnknown(m)
}

var xxx_messageInfo_CreditCardInfo proto.InternalMessageInfo

func (m *CreditCardInfo) GetCardNumber() string {
	if m != nil {
		return m.CardNumber
	}
	return ""
}

func (m *CreditCardInfo) GetCvc() string {
	if m != nil {
		return m.Cvc
	}
	return ""
}

type AddressInfo struct {
	Street               string   `protobuf:"bytes,1,opt,name=street,proto3" json:"street,omitempty"`
	PostalCode           string   `protobuf:"bytes,2,opt,name=postalCode,proto3" json:"postalCode,omitempty"`
	City                 string   `protobuf:"bytes,3,opt,name=city,proto3" json:"city,omitempty"`
	Province             string   `protobuf:"bytes,4,opt,name=province,proto3" json:"province,omitempty"`
	PhoneNumber          string   `protobuf:"bytes,5,opt,name=phoneNumber,proto3" json:"phoneNumber,omitempty"`
	Email                string   `protobuf:"bytes,6,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddressInfo) Reset()         { *m = AddressInfo{} }
func (m *AddressInfo) String() string { return proto.CompactTextString(m) }
func (*AddressInfo) ProtoMessage()    {}
func (*AddressInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{2}
}

func (m *AddressInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddressInfo.Unmarshal(m, b)
}
func (m *AddressInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddressInfo.Marshal(b, m, deterministic)
}
func (m *AddressInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddressInfo.Merge(m, src)
}
func (m *AddressInfo) XXX_Size() int {
	return xxx_messageInfo_AddressInfo.Size(m)
}
func (m *AddressInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_AddressInfo.DiscardUnknown(m)
}

var xxx_messageInfo_AddressInfo proto.InternalMessageInfo

func (m *AddressInfo) GetStreet() string {
	if m != nil {
		return m.Street
	}
	return ""
}

func (m *AddressInfo) GetPostalCode() string {
	if m != nil {
		return m.PostalCode
	}
	return ""
}

func (m *AddressInfo) GetCity() string {
	if m != nil {
		return m.City
	}
	return ""
}

func (m *AddressInfo) GetProvince() string {
	if m != nil {
		return m.Province
	}
	return ""
}

func (m *AddressInfo) GetPhoneNumber() string {
	if m != nil {
		return m.PhoneNumber
	}
	return ""
}

func (m *AddressInfo) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type ProfileInfo struct {
	FirstName            string   `protobuf:"bytes,1,opt,name=firstName,proto3" json:"firstName,omitempty"`
	Surname              string   `protobuf:"bytes,2,opt,name=surname,proto3" json:"surname,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProfileInfo) Reset()         { *m = ProfileInfo{} }
func (m *ProfileInfo) String() string { return proto.CompactTextString(m) }
func (*ProfileInfo) ProtoMessage()    {}
func (*ProfileInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{3}
}

func (m *ProfileInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProfileInfo.Unmarshal(m, b)
}
func (m *ProfileInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProfileInfo.Marshal(b, m, deterministic)
}
func (m *ProfileInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProfileInfo.Merge(m, src)
}
func (m *ProfileInfo) XXX_Size() int {
	return xxx_messageInfo_ProfileInfo.Size(m)
}
func (m *ProfileInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ProfileInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ProfileInfo proto.InternalMessageInfo

func (m *ProfileInfo) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *ProfileInfo) GetSurname() string {
	if m != nil {
		return m.Surname
	}
	return ""
}

type AddAccountRequest struct {
	ProfileInfo          *ProfileInfo    `protobuf:"bytes,1,opt,name=profileInfo,proto3" json:"profileInfo,omitempty"`
	LoginInfo            *LoginInfo      `protobuf:"bytes,2,opt,name=loginInfo,proto3" json:"loginInfo,omitempty"`
	AddressInfo          *AddressInfo    `protobuf:"bytes,3,opt,name=addressInfo,proto3" json:"addressInfo,omitempty"`
	CreditCardInfo       *CreditCardInfo `protobuf:"bytes,4,opt,name=creditCardInfo,proto3" json:"creditCardInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *AddAccountRequest) Reset()         { *m = AddAccountRequest{} }
func (m *AddAccountRequest) String() string { return proto.CompactTextString(m) }
func (*AddAccountRequest) ProtoMessage()    {}
func (*AddAccountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{4}
}

func (m *AddAccountRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddAccountRequest.Unmarshal(m, b)
}
func (m *AddAccountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddAccountRequest.Marshal(b, m, deterministic)
}
func (m *AddAccountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddAccountRequest.Merge(m, src)
}
func (m *AddAccountRequest) XXX_Size() int {
	return xxx_messageInfo_AddAccountRequest.Size(m)
}
func (m *AddAccountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddAccountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddAccountRequest proto.InternalMessageInfo

func (m *AddAccountRequest) GetProfileInfo() *ProfileInfo {
	if m != nil {
		return m.ProfileInfo
	}
	return nil
}

func (m *AddAccountRequest) GetLoginInfo() *LoginInfo {
	if m != nil {
		return m.LoginInfo
	}
	return nil
}

func (m *AddAccountRequest) GetAddressInfo() *AddressInfo {
	if m != nil {
		return m.AddressInfo
	}
	return nil
}

func (m *AddAccountRequest) GetCreditCardInfo() *CreditCardInfo {
	if m != nil {
		return m.CreditCardInfo
	}
	return nil
}

type AddAccountReponse struct {
	AccountNumber        string   `protobuf:"bytes,1,opt,name=accountNumber,proto3" json:"accountNumber,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddAccountReponse) Reset()         { *m = AddAccountReponse{} }
func (m *AddAccountReponse) String() string { return proto.CompactTextString(m) }
func (*AddAccountReponse) ProtoMessage()    {}
func (*AddAccountReponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{5}
}

func (m *AddAccountReponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddAccountReponse.Unmarshal(m, b)
}
func (m *AddAccountReponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddAccountReponse.Marshal(b, m, deterministic)
}
func (m *AddAccountReponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddAccountReponse.Merge(m, src)
}
func (m *AddAccountReponse) XXX_Size() int {
	return xxx_messageInfo_AddAccountReponse.Size(m)
}
func (m *AddAccountReponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddAccountReponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddAccountReponse proto.InternalMessageInfo

func (m *AddAccountReponse) GetAccountNumber() string {
	if m != nil {
		return m.AccountNumber
	}
	return ""
}

type AddCreditCardRequest struct {
	AccountNumber        string          `protobuf:"bytes,1,opt,name=accountNumber,proto3" json:"accountNumber,omitempty"`
	CreditCardInfo       *CreditCardInfo `protobuf:"bytes,2,opt,name=creditCardInfo,proto3" json:"creditCardInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *AddCreditCardRequest) Reset()         { *m = AddCreditCardRequest{} }
func (m *AddCreditCardRequest) String() string { return proto.CompactTextString(m) }
func (*AddCreditCardRequest) ProtoMessage()    {}
func (*AddCreditCardRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{6}
}

func (m *AddCreditCardRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddCreditCardRequest.Unmarshal(m, b)
}
func (m *AddCreditCardRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddCreditCardRequest.Marshal(b, m, deterministic)
}
func (m *AddCreditCardRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddCreditCardRequest.Merge(m, src)
}
func (m *AddCreditCardRequest) XXX_Size() int {
	return xxx_messageInfo_AddCreditCardRequest.Size(m)
}
func (m *AddCreditCardRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddCreditCardRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddCreditCardRequest proto.InternalMessageInfo

func (m *AddCreditCardRequest) GetAccountNumber() string {
	if m != nil {
		return m.AccountNumber
	}
	return ""
}

func (m *AddCreditCardRequest) GetCreditCardInfo() *CreditCardInfo {
	if m != nil {
		return m.CreditCardInfo
	}
	return nil
}

type AddCreditCardResponse struct {
	AccountNumber        string   `protobuf:"bytes,1,opt,name=accountNumber,proto3" json:"accountNumber,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddCreditCardResponse) Reset()         { *m = AddCreditCardResponse{} }
func (m *AddCreditCardResponse) String() string { return proto.CompactTextString(m) }
func (*AddCreditCardResponse) ProtoMessage()    {}
func (*AddCreditCardResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{7}
}

func (m *AddCreditCardResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddCreditCardResponse.Unmarshal(m, b)
}
func (m *AddCreditCardResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddCreditCardResponse.Marshal(b, m, deterministic)
}
func (m *AddCreditCardResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddCreditCardResponse.Merge(m, src)
}
func (m *AddCreditCardResponse) XXX_Size() int {
	return xxx_messageInfo_AddCreditCardResponse.Size(m)
}
func (m *AddCreditCardResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddCreditCardResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddCreditCardResponse proto.InternalMessageInfo

func (m *AddCreditCardResponse) GetAccountNumber() string {
	if m != nil {
		return m.AccountNumber
	}
	return ""
}

type AddresssUpdateRequest struct {
	AccountNumber        string       `protobuf:"bytes,1,opt,name=accountNumber,proto3" json:"accountNumber,omitempty"`
	AddressInfo          *AddressInfo `protobuf:"bytes,2,opt,name=addressInfo,proto3" json:"addressInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *AddresssUpdateRequest) Reset()         { *m = AddresssUpdateRequest{} }
func (m *AddresssUpdateRequest) String() string { return proto.CompactTextString(m) }
func (*AddresssUpdateRequest) ProtoMessage()    {}
func (*AddresssUpdateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{8}
}

func (m *AddresssUpdateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddresssUpdateRequest.Unmarshal(m, b)
}
func (m *AddresssUpdateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddresssUpdateRequest.Marshal(b, m, deterministic)
}
func (m *AddresssUpdateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddresssUpdateRequest.Merge(m, src)
}
func (m *AddresssUpdateRequest) XXX_Size() int {
	return xxx_messageInfo_AddresssUpdateRequest.Size(m)
}
func (m *AddresssUpdateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddresssUpdateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddresssUpdateRequest proto.InternalMessageInfo

func (m *AddresssUpdateRequest) GetAccountNumber() string {
	if m != nil {
		return m.AccountNumber
	}
	return ""
}

func (m *AddresssUpdateRequest) GetAddressInfo() *AddressInfo {
	if m != nil {
		return m.AddressInfo
	}
	return nil
}

type AddressUpdateResponse struct {
	AccountNumber        string   `protobuf:"bytes,1,opt,name=accountNumber,proto3" json:"accountNumber,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddressUpdateResponse) Reset()         { *m = AddressUpdateResponse{} }
func (m *AddressUpdateResponse) String() string { return proto.CompactTextString(m) }
func (*AddressUpdateResponse) ProtoMessage()    {}
func (*AddressUpdateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{9}
}

func (m *AddressUpdateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddressUpdateResponse.Unmarshal(m, b)
}
func (m *AddressUpdateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddressUpdateResponse.Marshal(b, m, deterministic)
}
func (m *AddressUpdateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddressUpdateResponse.Merge(m, src)
}
func (m *AddressUpdateResponse) XXX_Size() int {
	return xxx_messageInfo_AddressUpdateResponse.Size(m)
}
func (m *AddressUpdateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddressUpdateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddressUpdateResponse proto.InternalMessageInfo

func (m *AddressUpdateResponse) GetAccountNumber() string {
	if m != nil {
		return m.AccountNumber
	}
	return ""
}

type ProfileUpdateRequest struct {
	AccountNumber        string       `protobuf:"bytes,1,opt,name=accountNumber,proto3" json:"accountNumber,omitempty"`
	ProfileInfo          *ProfileInfo `protobuf:"bytes,2,opt,name=profileInfo,proto3" json:"profileInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ProfileUpdateRequest) Reset()         { *m = ProfileUpdateRequest{} }
func (m *ProfileUpdateRequest) String() string { return proto.CompactTextString(m) }
func (*ProfileUpdateRequest) ProtoMessage()    {}
func (*ProfileUpdateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{10}
}

func (m *ProfileUpdateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProfileUpdateRequest.Unmarshal(m, b)
}
func (m *ProfileUpdateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProfileUpdateRequest.Marshal(b, m, deterministic)
}
func (m *ProfileUpdateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProfileUpdateRequest.Merge(m, src)
}
func (m *ProfileUpdateRequest) XXX_Size() int {
	return xxx_messageInfo_ProfileUpdateRequest.Size(m)
}
func (m *ProfileUpdateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ProfileUpdateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ProfileUpdateRequest proto.InternalMessageInfo

func (m *ProfileUpdateRequest) GetAccountNumber() string {
	if m != nil {
		return m.AccountNumber
	}
	return ""
}

func (m *ProfileUpdateRequest) GetProfileInfo() *ProfileInfo {
	if m != nil {
		return m.ProfileInfo
	}
	return nil
}

type ProfileUpdateResponse struct {
	AccountNumber        string   `protobuf:"bytes,1,opt,name=accountNumber,proto3" json:"accountNumber,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProfileUpdateResponse) Reset()         { *m = ProfileUpdateResponse{} }
func (m *ProfileUpdateResponse) String() string { return proto.CompactTextString(m) }
func (*ProfileUpdateResponse) ProtoMessage()    {}
func (*ProfileUpdateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{11}
}

func (m *ProfileUpdateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProfileUpdateResponse.Unmarshal(m, b)
}
func (m *ProfileUpdateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProfileUpdateResponse.Marshal(b, m, deterministic)
}
func (m *ProfileUpdateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProfileUpdateResponse.Merge(m, src)
}
func (m *ProfileUpdateResponse) XXX_Size() int {
	return xxx_messageInfo_ProfileUpdateResponse.Size(m)
}
func (m *ProfileUpdateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ProfileUpdateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ProfileUpdateResponse proto.InternalMessageInfo

func (m *ProfileUpdateResponse) GetAccountNumber() string {
	if m != nil {
		return m.AccountNumber
	}
	return ""
}

type BalanceRequest struct {
	AccountNumber        string   `protobuf:"bytes,1,opt,name=accountNumber,proto3" json:"accountNumber,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BalanceRequest) Reset()         { *m = BalanceRequest{} }
func (m *BalanceRequest) String() string { return proto.CompactTextString(m) }
func (*BalanceRequest) ProtoMessage()    {}
func (*BalanceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{12}
}

func (m *BalanceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BalanceRequest.Unmarshal(m, b)
}
func (m *BalanceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BalanceRequest.Marshal(b, m, deterministic)
}
func (m *BalanceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BalanceRequest.Merge(m, src)
}
func (m *BalanceRequest) XXX_Size() int {
	return xxx_messageInfo_BalanceRequest.Size(m)
}
func (m *BalanceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BalanceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BalanceRequest proto.InternalMessageInfo

func (m *BalanceRequest) GetAccountNumber() string {
	if m != nil {
		return m.AccountNumber
	}
	return ""
}

type BalanceResponse struct {
	Balance              float64  `protobuf:"fixed64,1,opt,name=balance,proto3" json:"balance,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BalanceResponse) Reset()         { *m = BalanceResponse{} }
func (m *BalanceResponse) String() string { return proto.CompactTextString(m) }
func (*BalanceResponse) ProtoMessage()    {}
func (*BalanceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{13}
}

func (m *BalanceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BalanceResponse.Unmarshal(m, b)
}
func (m *BalanceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BalanceResponse.Marshal(b, m, deterministic)
}
func (m *BalanceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BalanceResponse.Merge(m, src)
}
func (m *BalanceResponse) XXX_Size() int {
	return xxx_messageInfo_BalanceResponse.Size(m)
}
func (m *BalanceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BalanceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BalanceResponse proto.InternalMessageInfo

func (m *BalanceResponse) GetBalance() float64 {
	if m != nil {
		return m.Balance
	}
	return 0
}

type CreditCardsRequest struct {
	AccountNumber        string   `protobuf:"bytes,1,opt,name=accountNumber,proto3" json:"accountNumber,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreditCardsRequest) Reset()         { *m = CreditCardsRequest{} }
func (m *CreditCardsRequest) String() string { return proto.CompactTextString(m) }
func (*CreditCardsRequest) ProtoMessage()    {}
func (*CreditCardsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{14}
}

func (m *CreditCardsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreditCardsRequest.Unmarshal(m, b)
}
func (m *CreditCardsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreditCardsRequest.Marshal(b, m, deterministic)
}
func (m *CreditCardsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreditCardsRequest.Merge(m, src)
}
func (m *CreditCardsRequest) XXX_Size() int {
	return xxx_messageInfo_CreditCardsRequest.Size(m)
}
func (m *CreditCardsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreditCardsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreditCardsRequest proto.InternalMessageInfo

func (m *CreditCardsRequest) GetAccountNumber() string {
	if m != nil {
		return m.AccountNumber
	}
	return ""
}

type CreditCardsResponse struct {
	CreditCards          []*CreditCardInfo `protobuf:"bytes,1,rep,name=creditCards,proto3" json:"creditCards,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *CreditCardsResponse) Reset()         { *m = CreditCardsResponse{} }
func (m *CreditCardsResponse) String() string { return proto.CompactTextString(m) }
func (*CreditCardsResponse) ProtoMessage()    {}
func (*CreditCardsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{15}
}

func (m *CreditCardsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreditCardsResponse.Unmarshal(m, b)
}
func (m *CreditCardsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreditCardsResponse.Marshal(b, m, deterministic)
}
func (m *CreditCardsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreditCardsResponse.Merge(m, src)
}
func (m *CreditCardsResponse) XXX_Size() int {
	return xxx_messageInfo_CreditCardsResponse.Size(m)
}
func (m *CreditCardsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreditCardsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreditCardsResponse proto.InternalMessageInfo

func (m *CreditCardsResponse) GetCreditCards() []*CreditCardInfo {
	if m != nil {
		return m.CreditCards
	}
	return nil
}

type ProfileRequest struct {
	AccountNumber        string   `protobuf:"bytes,1,opt,name=accountNumber,proto3" json:"accountNumber,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProfileRequest) Reset()         { *m = ProfileRequest{} }
func (m *ProfileRequest) String() string { return proto.CompactTextString(m) }
func (*ProfileRequest) ProtoMessage()    {}
func (*ProfileRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{16}
}

func (m *ProfileRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProfileRequest.Unmarshal(m, b)
}
func (m *ProfileRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProfileRequest.Marshal(b, m, deterministic)
}
func (m *ProfileRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProfileRequest.Merge(m, src)
}
func (m *ProfileRequest) XXX_Size() int {
	return xxx_messageInfo_ProfileRequest.Size(m)
}
func (m *ProfileRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ProfileRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ProfileRequest proto.InternalMessageInfo

func (m *ProfileRequest) GetAccountNumber() string {
	if m != nil {
		return m.AccountNumber
	}
	return ""
}

type ProfileResponse struct {
	ProfileInfo          *ProfileInfo `protobuf:"bytes,1,opt,name=profileInfo,proto3" json:"profileInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ProfileResponse) Reset()         { *m = ProfileResponse{} }
func (m *ProfileResponse) String() string { return proto.CompactTextString(m) }
func (*ProfileResponse) ProtoMessage()    {}
func (*ProfileResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{17}
}

func (m *ProfileResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProfileResponse.Unmarshal(m, b)
}
func (m *ProfileResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProfileResponse.Marshal(b, m, deterministic)
}
func (m *ProfileResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProfileResponse.Merge(m, src)
}
func (m *ProfileResponse) XXX_Size() int {
	return xxx_messageInfo_ProfileResponse.Size(m)
}
func (m *ProfileResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ProfileResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ProfileResponse proto.InternalMessageInfo

func (m *ProfileResponse) GetProfileInfo() *ProfileInfo {
	if m != nil {
		return m.ProfileInfo
	}
	return nil
}

func init() {
	proto.RegisterType((*LoginInfo)(nil), "LoginInfo")
	proto.RegisterType((*CreditCardInfo)(nil), "CreditCardInfo")
	proto.RegisterType((*AddressInfo)(nil), "AddressInfo")
	proto.RegisterType((*ProfileInfo)(nil), "ProfileInfo")
	proto.RegisterType((*AddAccountRequest)(nil), "AddAccountRequest")
	proto.RegisterType((*AddAccountReponse)(nil), "AddAccountReponse")
	proto.RegisterType((*AddCreditCardRequest)(nil), "AddCreditCardRequest")
	proto.RegisterType((*AddCreditCardResponse)(nil), "AddCreditCardResponse")
	proto.RegisterType((*AddresssUpdateRequest)(nil), "AddresssUpdateRequest")
	proto.RegisterType((*AddressUpdateResponse)(nil), "AddressUpdateResponse")
	proto.RegisterType((*ProfileUpdateRequest)(nil), "ProfileUpdateRequest")
	proto.RegisterType((*ProfileUpdateResponse)(nil), "ProfileUpdateResponse")
	proto.RegisterType((*BalanceRequest)(nil), "BalanceRequest")
	proto.RegisterType((*BalanceResponse)(nil), "BalanceResponse")
	proto.RegisterType((*CreditCardsRequest)(nil), "CreditCardsRequest")
	proto.RegisterType((*CreditCardsResponse)(nil), "CreditCardsResponse")
	proto.RegisterType((*ProfileRequest)(nil), "ProfileRequest")
	proto.RegisterType((*ProfileResponse)(nil), "ProfileResponse")
}

func init() { proto.RegisterFile("account.proto", fileDescriptor_8e28828dcb8d24f0) }

var fileDescriptor_8e28828dcb8d24f0 = []byte{
	// 644 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x55, 0xeb, 0x6a, 0xdb, 0x4c,
	0x10, 0x45, 0x76, 0x2e, 0x9f, 0x47, 0x5f, 0xe2, 0x64, 0xe3, 0x18, 0x21, 0x4a, 0x09, 0xa2, 0x3f,
	0x02, 0x85, 0x85, 0xba, 0x25, 0xbd, 0x40, 0x53, 0x6c, 0x53, 0xda, 0x42, 0x09, 0x45, 0xa5, 0x0f,
	0xb0, 0xd6, 0xae, 0x5d, 0x81, 0xac, 0x55, 0x77, 0x57, 0x2e, 0x79, 0xa8, 0x3e, 0x46, 0x5f, 0xa1,
	0xcf, 0x53, 0xb4, 0x5a, 0x5d, 0x23, 0x48, 0xd4, 0x7f, 0x9a, 0x99, 0x9d, 0x33, 0x67, 0x67, 0xce,
	0xac, 0xe0, 0x88, 0x04, 0x01, 0x4f, 0x63, 0x85, 0x13, 0xc1, 0x15, 0xf7, 0x96, 0x30, 0xfa, 0xcc,
	0x37, 0x61, 0xfc, 0x29, 0x5e, 0x73, 0xe4, 0xc2, 0x7f, 0xa9, 0x64, 0x22, 0x26, 0x5b, 0xe6, 0x58,
	0x17, 0xd6, 0xe5, 0xc8, 0x2f, 0xed, 0x2c, 0x96, 0x10, 0x29, 0x7f, 0x72, 0x41, 0x9d, 0x41, 0x1e,
	0x2b, 0x6c, 0x6f, 0x01, 0xc7, 0x4b, 0xc1, 0x68, 0xa8, 0x96, 0x44, 0x50, 0x8d, 0xf4, 0x18, 0x20,
	0x20, 0x82, 0xde, 0xa4, 0xdb, 0x15, 0x13, 0x06, 0xab, 0xe6, 0x41, 0x27, 0x30, 0x0c, 0x76, 0x81,
	0x01, 0xca, 0x3e, 0xbd, 0x5f, 0x16, 0xd8, 0x73, 0x4a, 0x05, 0x93, 0x52, 0x23, 0x4c, 0xe1, 0x40,
	0x2a, 0xc1, 0x98, 0x32, 0xd9, 0xc6, 0xca, 0x90, 0x13, 0x2e, 0x15, 0x89, 0x96, 0x9c, 0x32, 0x03,
	0x50, 0xf3, 0x20, 0x04, 0x7b, 0x41, 0xa8, 0x6e, 0x9d, 0xa1, 0x8e, 0xe8, 0x6f, 0xcd, 0x5d, 0xf0,
	0x5d, 0x18, 0x07, 0xcc, 0xd9, 0x33, 0xdc, 0x8d, 0x8d, 0x2e, 0xc0, 0x4e, 0xbe, 0xf3, 0x98, 0x19,
	0xaa, 0xfb, 0x3a, 0x5c, 0x77, 0xa1, 0x09, 0xec, 0xb3, 0x2d, 0x09, 0x23, 0xe7, 0x40, 0xc7, 0x72,
	0xc3, 0x7b, 0x0f, 0xf6, 0x17, 0xc1, 0xd7, 0x61, 0xc4, 0x34, 0xdd, 0x47, 0x30, 0x5a, 0x87, 0x42,
	0xaa, 0x9b, 0xaa, 0x77, 0x95, 0x03, 0x39, 0x70, 0x28, 0xd3, 0xbc, 0xaf, 0x39, 0xe3, 0xc2, 0xf4,
	0xfe, 0x58, 0x70, 0x3a, 0xa7, 0x74, 0x9e, 0x0f, 0xc5, 0x67, 0x3f, 0x52, 0x26, 0x15, 0xc2, 0x60,
	0x27, 0x15, 0xb8, 0xc6, 0xb3, 0x67, 0xff, 0xe3, 0x5a, 0x41, 0xbf, 0x7e, 0x00, 0x5d, 0xc2, 0x28,
	0x2a, 0xa6, 0xa8, 0x2b, 0xd8, 0x33, 0xc0, 0xe5, 0x5c, 0xfd, 0x2a, 0x98, 0x21, 0x93, 0xaa, 0xcb,
	0xba, 0x4b, 0x19, 0x72, 0xad, 0xf3, 0x7e, 0xfd, 0x00, 0x7a, 0x09, 0xc7, 0x41, 0x63, 0xb4, 0xba,
	0x81, 0xf6, 0x6c, 0x8c, 0x9b, 0x13, 0xf7, 0x5b, 0xc7, 0xbc, 0xd7, 0xcd, 0x7b, 0x25, 0x3c, 0x96,
	0x0c, 0x3d, 0x29, 0xe5, 0xd7, 0x50, 0x46, 0xd3, 0xe9, 0xa5, 0x30, 0x99, 0x53, 0x5a, 0xe1, 0x17,
	0x5d, 0x79, 0x50, 0x76, 0x07, 0xe3, 0xc1, 0xc3, 0x18, 0xbf, 0x85, 0xf3, 0x56, 0x59, 0xd9, 0x87,
	0xf5, 0x56, 0xa7, 0x67, 0x8d, 0x93, 0xdf, 0x12, 0x4a, 0x14, 0xeb, 0x47, 0xbb, 0x35, 0x98, 0xc1,
	0x3d, 0x83, 0x31, 0x6c, 0x33, 0xb3, 0xa8, 0xd6, 0x8b, 0x6d, 0x04, 0x13, 0xa3, 0xa6, 0x7f, 0x24,
	0x5b, 0xd7, 0xe7, 0xe0, 0x1e, 0x7d, 0x66, 0x64, 0x5b, 0xd5, 0x7a, 0x91, 0xbd, 0x82, 0xe3, 0x05,
	0x89, 0x48, 0x1c, 0xf4, 0xa3, 0xe9, 0x3d, 0x85, 0x71, 0x99, 0x67, 0x0a, 0x3a, 0x70, 0xb8, 0xca,
	0x5d, 0x3a, 0xc5, 0xf2, 0x0b, 0xd3, 0x7b, 0x03, 0xa8, 0x9a, 0xbd, 0xec, 0x57, 0xe8, 0x23, 0x9c,
	0x35, 0x72, 0x4d, 0xb1, 0x67, 0x60, 0x57, 0x1a, 0x93, 0x8e, 0x75, 0x31, 0xec, 0xd2, 0x61, 0xfd,
	0x4c, 0x76, 0x55, 0xd3, 0xa9, 0x7e, 0x0c, 0xe6, 0x30, 0x2e, 0xf3, 0x4c, 0xf5, 0x9e, 0x8f, 0xc8,
	0xec, 0xf7, 0x10, 0x4e, 0x8b, 0x7d, 0x4d, 0x82, 0xaf, 0x4c, 0xec, 0xc2, 0x80, 0xa1, 0x17, 0x00,
	0xa4, 0xdc, 0x63, 0x84, 0xf0, 0x9d, 0xc7, 0xca, 0x6d, 0xfa, 0xf2, 0xda, 0xd7, 0x70, 0x44, 0xea,
	0xbb, 0x84, 0xce, 0x71, 0xd7, 0x4a, 0xbb, 0x53, 0xdc, 0xbd, 0x72, 0xef, 0xe0, 0x28, 0xd5, 0x4a,
	0x31, 0x1a, 0x47, 0x53, 0xdc, 0xb9, 0x5c, 0x6e, 0xe9, 0x6f, 0x09, 0xeb, 0xba, 0x00, 0x30, 0xd7,
	0x45, 0xe7, 0xb8, 0x4b, 0xef, 0xee, 0x14, 0x77, 0x0b, 0xf3, 0x0a, 0x4e, 0x37, 0x4c, 0x99, 0x5b,
	0x19, 0x11, 0xa1, 0x31, 0x6e, 0xca, 0xd0, 0x3d, 0xc1, 0x6d, 0x7d, 0x7d, 0x00, 0x37, 0xcb, 0x8b,
	0xa2, 0x9a, 0x1e, 0x16, 0xb7, 0x45, 0xfb, 0xce, 0xf0, 0x5d, 0x89, 0xb9, 0x13, 0xdc, 0xa5, 0x9d,
	0x57, 0x70, 0xb6, 0x61, 0xca, 0x90, 0xab, 0x10, 0xc6, 0xb8, 0x29, 0x0f, 0xf7, 0x04, 0xb7, 0xe6,
	0xbe, 0x3a, 0xd0, 0x7f, 0xf6, 0xe7, 0x7f, 0x03, 0x00, 0x00, 0xff, 0xff, 0x48, 0xb6, 0x57, 0xd1,
	0xea, 0x07, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AccountRpcServiceClient is the client API for AccountRpcService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AccountRpcServiceClient interface {
	AddAccount(ctx context.Context, in *AddAccountRequest, opts ...grpc.CallOption) (*AddAccountReponse, error)
	AddCreditCard(ctx context.Context, in *AddCreditCardRequest, opts ...grpc.CallOption) (*AddCreditCardResponse, error)
	UpdateAddress(ctx context.Context, in *AddresssUpdateRequest, opts ...grpc.CallOption) (*AddressUpdateResponse, error)
	UpdateProfile(ctx context.Context, in *ProfileUpdateRequest, opts ...grpc.CallOption) (*ProfileUpdateResponse, error)
	GetAccountBalance(ctx context.Context, in *BalanceRequest, opts ...grpc.CallOption) (*BalanceResponse, error)
	GetAllCreditCardsByAccount(ctx context.Context, in *CreditCardsRequest, opts ...grpc.CallOption) (*CreditCardsResponse, error)
	GetProfileByAccount(ctx context.Context, in *ProfileRequest, opts ...grpc.CallOption) (*ProfileResponse, error)
}

type accountRpcServiceClient struct {
	cc *grpc.ClientConn
}

func NewAccountRpcServiceClient(cc *grpc.ClientConn) AccountRpcServiceClient {
	return &accountRpcServiceClient{cc}
}

func (c *accountRpcServiceClient) AddAccount(ctx context.Context, in *AddAccountRequest, opts ...grpc.CallOption) (*AddAccountReponse, error) {
	out := new(AddAccountReponse)
	err := c.cc.Invoke(ctx, "/AccountRpcService/addAccount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountRpcServiceClient) AddCreditCard(ctx context.Context, in *AddCreditCardRequest, opts ...grpc.CallOption) (*AddCreditCardResponse, error) {
	out := new(AddCreditCardResponse)
	err := c.cc.Invoke(ctx, "/AccountRpcService/addCreditCard", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountRpcServiceClient) UpdateAddress(ctx context.Context, in *AddresssUpdateRequest, opts ...grpc.CallOption) (*AddressUpdateResponse, error) {
	out := new(AddressUpdateResponse)
	err := c.cc.Invoke(ctx, "/AccountRpcService/updateAddress", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountRpcServiceClient) UpdateProfile(ctx context.Context, in *ProfileUpdateRequest, opts ...grpc.CallOption) (*ProfileUpdateResponse, error) {
	out := new(ProfileUpdateResponse)
	err := c.cc.Invoke(ctx, "/AccountRpcService/updateProfile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountRpcServiceClient) GetAccountBalance(ctx context.Context, in *BalanceRequest, opts ...grpc.CallOption) (*BalanceResponse, error) {
	out := new(BalanceResponse)
	err := c.cc.Invoke(ctx, "/AccountRpcService/getAccountBalance", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountRpcServiceClient) GetAllCreditCardsByAccount(ctx context.Context, in *CreditCardsRequest, opts ...grpc.CallOption) (*CreditCardsResponse, error) {
	out := new(CreditCardsResponse)
	err := c.cc.Invoke(ctx, "/AccountRpcService/getAllCreditCardsByAccount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountRpcServiceClient) GetProfileByAccount(ctx context.Context, in *ProfileRequest, opts ...grpc.CallOption) (*ProfileResponse, error) {
	out := new(ProfileResponse)
	err := c.cc.Invoke(ctx, "/AccountRpcService/getProfileByAccount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AccountRpcServiceServer is the server API for AccountRpcService service.
type AccountRpcServiceServer interface {
	AddAccount(context.Context, *AddAccountRequest) (*AddAccountReponse, error)
	AddCreditCard(context.Context, *AddCreditCardRequest) (*AddCreditCardResponse, error)
	UpdateAddress(context.Context, *AddresssUpdateRequest) (*AddressUpdateResponse, error)
	UpdateProfile(context.Context, *ProfileUpdateRequest) (*ProfileUpdateResponse, error)
	GetAccountBalance(context.Context, *BalanceRequest) (*BalanceResponse, error)
	GetAllCreditCardsByAccount(context.Context, *CreditCardsRequest) (*CreditCardsResponse, error)
	GetProfileByAccount(context.Context, *ProfileRequest) (*ProfileResponse, error)
}

func RegisterAccountRpcServiceServer(s *grpc.Server, srv AccountRpcServiceServer) {
	s.RegisterService(&_AccountRpcService_serviceDesc, srv)
}

func _AccountRpcService_AddAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountRpcServiceServer).AddAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/AccountRpcService/AddAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountRpcServiceServer).AddAccount(ctx, req.(*AddAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountRpcService_AddCreditCard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddCreditCardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountRpcServiceServer).AddCreditCard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/AccountRpcService/AddCreditCard",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountRpcServiceServer).AddCreditCard(ctx, req.(*AddCreditCardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountRpcService_UpdateAddress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddresssUpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountRpcServiceServer).UpdateAddress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/AccountRpcService/UpdateAddress",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountRpcServiceServer).UpdateAddress(ctx, req.(*AddresssUpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountRpcService_UpdateProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProfileUpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountRpcServiceServer).UpdateProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/AccountRpcService/UpdateProfile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountRpcServiceServer).UpdateProfile(ctx, req.(*ProfileUpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountRpcService_GetAccountBalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BalanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountRpcServiceServer).GetAccountBalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/AccountRpcService/GetAccountBalance",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountRpcServiceServer).GetAccountBalance(ctx, req.(*BalanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountRpcService_GetAllCreditCardsByAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreditCardsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountRpcServiceServer).GetAllCreditCardsByAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/AccountRpcService/GetAllCreditCardsByAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountRpcServiceServer).GetAllCreditCardsByAccount(ctx, req.(*CreditCardsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountRpcService_GetProfileByAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountRpcServiceServer).GetProfileByAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/AccountRpcService/GetProfileByAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountRpcServiceServer).GetProfileByAccount(ctx, req.(*ProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AccountRpcService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "AccountRpcService",
	HandlerType: (*AccountRpcServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "addAccount",
			Handler:    _AccountRpcService_AddAccount_Handler,
		},
		{
			MethodName: "addCreditCard",
			Handler:    _AccountRpcService_AddCreditCard_Handler,
		},
		{
			MethodName: "updateAddress",
			Handler:    _AccountRpcService_UpdateAddress_Handler,
		},
		{
			MethodName: "updateProfile",
			Handler:    _AccountRpcService_UpdateProfile_Handler,
		},
		{
			MethodName: "getAccountBalance",
			Handler:    _AccountRpcService_GetAccountBalance_Handler,
		},
		{
			MethodName: "getAllCreditCardsByAccount",
			Handler:    _AccountRpcService_GetAllCreditCardsByAccount_Handler,
		},
		{
			MethodName: "getProfileByAccount",
			Handler:    _AccountRpcService_GetProfileByAccount_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "account.proto",
}
